## Contribution Coefficient Variation

단계별 공헌계수가 변동하는 경우의 분석사례로서, 앞에서 수행한 최대화의 문제를 참조하여 다음 문제를 고려하였다. 즉, 어느 회사에서 x1, x2, 2개 제푸믈 생산하여 판매한다. 제품을 생산하여 판매하면 제품수량에 따라 x1은 4, 3, 2만원 제품x2는 3, 2, 1만 원의 이익이 발생한다. 제품의 생산과정에서는 A, B, C 3개 자원이 소모되며, 제품별로 소요되는 A, B, C 자원의 량과 각 자원별 최대 사용 가능량은 다음과 같다.

|소요자원|제품 X1|제품 X2|사용가능 자원량|
|:----:|-----:|-----:|--------:|
|A|2|3|80|
|B|-3|2|20|
|C|2|1|50|
|이익|4(0-10개)|3(0-10개)||
||3(11-20개)|2(11-20개)||
||2(20개 이상)|1(21개 이상)||

In [ ]:
from pulp import *

prob = LpProblem("Contribution Coefficient Variation", LpMaximize)

In [ ]:
y1 = LpVariable("Y1", lowBound=0)
y2 = LpVariable("Y2", lowBound=0)
y3 = LpVariable("Y3", lowBound=0)
y4 = LpVariable("Y4", lowBound=0)
y5 = LpVariable("Y5", lowBound=0)
y6 = LpVariable("Y6", lowBound=0)

In [ ]:
prob += 4*y1 + 3*y2 + 2*y3 + 3*y4 + 2*y5 + y6

In [ ]:
prob += 2*(y1+y2+y3) + 3*(y4+y5+y6) <= 80
prob += -3*(y1+y2+y3) + 2*(y4+y5+y6) <= 20
prob += 2*(y1+y2+y3) + (y4+y5+y6) <= 50

prob += y1 <= 10
prob += y2 <= 10
prob += y4 <= 10
prob += y5 <= 10

In [6]:
prob.solve()

1

In [7]:
for i in prob.variables():
    print(i.name, '=', i.varValue)
print('Status', LpStatus[prob.status])
print(pulp.value(prob.objective))

Y1 = 10.0
Y2 = 7.5
Y3 = 0.0
Y4 = 10.0
Y5 = 5.0
Y6 = 0.0
Status Optimal
102.5


### Housing Location Problem - Herbert Stevens

소득계층별 주거형태별 건설계획을 결정하는 분석사례이다. 예를 들어 어느 도시에서 1지역 면적 500ha, 2지역 면적은 300ha이며, 이 두 지역에, 고소득 300가구, 저소득 200가구 주택을 건설하고자 한다. 이때 소득별 주거형태별 주거비용, 소요예산, 그리고 소요면적은 다음과 같다. 이러한 상황에서 지대 절약을 최대로 하는 주택 건설 계획을 수립하시오.

|구분|주거비용|     |     |     |예산  |     |소요면적|    |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|   |1지역  |     |2지역 |     |     |     |    |    |
|   |주택 1 |주택 2|주택 1|주택 2|주택 1|주택 2|주택 1|주택 2|
|고소득|5|5|7|6|12|10|2.0|1.5|
|저소득|4|4|4|4|6|5|1.2|1.0|


|구분|가처분소득||(예산-주거비용)||
|:--:|:--:|:--:|:--:|:--:|
|   |1지역  |     |  2지역|    |
|   |주택 1 |주택 2|주택 1|주택 2|
|고소득|7 (X11)|5 (X12)|5 (X13)|4 (X14)|
|저소득|2 (X21)|1 (X22)|2 (X23)|1 (X24)|

In [8]:
prob = LpProblem("Housing Location Problem", LpMaximize)

In [9]:
X11 = LpVariable("X11", lowBound=0)
X12 = LpVariable("X12", lowBound=0)
X13 = LpVariable("X13", lowBound=0)
X14 = LpVariable("X14", lowBound=0)
X21 = LpVariable("X21", lowBound=0)
X22 = LpVariable("X22", lowBound=0)
X23 = LpVariable("X23", lowBound=0)
X24 = LpVariable("X24", lowBound=0)

In [10]:
prob += 7*X11 + 5*X12 + 5*X13 + 4*X14 + 2*X21 + X22 + 2*X23 + X24

In [11]:
prob += 2*X11 + 1.5*X12 + 1.2*X21 + X22 <= 500
prob += 2*X13 + 1.5*X14 + 1.2*X23 + X24 <= 300
prob += X11 + X12 + X13 + X14 <= 300
prob += X21 + X22 + X23 + X24 <= 200

In [12]:
prob.solve()

1

In [13]:
for i in prob.variables():
    print(i.name, "=", i.varValue)
print('Status', LpStatus[prob.status])
print(pulp.value(prob.objective))

X11 = 250.0
X12 = 0.0
X13 = 50.0
X14 = 0.0
X21 = 0.0
X22 = 0.0
X23 = 166.66667
X24 = 0.0
Status Optimal
2333.33334


## Transportation Programming

### 4.1 수송계획법의 개요

수송계획법은 선형게획법의 특수한 형태로서, 일반적으로 목적함수는 비용의 최소화이다. 수송계획 법의 수식형태와 적용변수들은 다음과 같으며, 수요와 공급이 일치할 경우, 제약조건은 등식이나, 수요와 공급이 불일치할 경우, 제약조건은 부등식이 된다.

* 목적함수(objective function): $\min \sum_{i=1}^n\sum_{j=1}^mc_{ij}x_{ij}$
* 제약조건(constraints): $\sum_{i=1}^nx_{ij}=S_i,\qquad\sum_{i=1}^mx_{ij}=D_j$
* Decision variable: $x_{ij}$, 결정변수로서 공급지역 i에서 수요지역 j로 이동하는 물동량으로 기저변수(basic variable)일 경우 물동량 할당이 된다.

|구분|   |수요|   |   |   |총공급량|
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|   |   |X  |Y  |Z  |W   |   |
|공급|A|21|12|25|11|80|
||B|13|10|21|17|60|
||C|12|14|19|12|50|
|총수요량||50|40|70|30|190|

In [14]:
prob = LpProblem("Transportation", LpMinimize)

In [15]:
S = ["A", "B", "C"]
D = ["1", "2", "3", "4"]
costs = [[21, 12, 25, 11],
         [13, 10, 21, 17],
         [12, 14, 19, 12]]

supply = dict(zip(S, [80, 60, 50]))
demand = dict(zip(D, [50, 40, 70, 30]))
demand

{'1': 50, '2': 40, '3': 70, '4': 30}

In [16]:
opt_costs = makeDict([S, D], costs, 0)
opt_costs

defaultdict(<function pulp.pulp.__makeDict.<locals>.<lambda>>,
            {'A': defaultdict(<function pulp.pulp.__makeDict.<locals>.<lambda>>,
                         {'1': 21, '2': 12, '3': 25, '4': 11}),
             'B': defaultdict(<function pulp.pulp.__makeDict.<locals>.<lambda>>,
                         {'1': 13, '2': 10, '3': 21, '4': 17}),
             'C': defaultdict(<function pulp.pulp.__makeDict.<locals>.<lambda>>,
                         {'1': 12, '2': 14, '3': 19, '4': 12})})

In [17]:
x = LpVariable.dicts('Route', (S, D), lowBound=0)
x

{'A': {'1': Route_A_1, '2': Route_A_2, '3': Route_A_3, '4': Route_A_4},
 'B': {'1': Route_B_1, '2': Route_B_2, '3': Route_B_3, '4': Route_B_4},
 'C': {'1': Route_C_1, '2': Route_C_2, '3': Route_C_3, '4': Route_C_4}}

In [18]:
routes = [(i, j) for i in S for j in D]
routes

[('A', '1'),
 ('A', '2'),
 ('A', '3'),
 ('A', '4'),
 ('B', '1'),
 ('B', '2'),
 ('B', '3'),
 ('B', '4'),
 ('C', '1'),
 ('C', '2'),
 ('C', '3'),
 ('C', '4')]

In [19]:
prob += lpSum([x[s][d]*opt_costs[s][d] for (s, d) in routes]) # objective function

# constraints
for i in S:
    prob += lpSum([x[i][j] for j in D]) == supply[i]

for j in D:
    prob += lpSum([x[i][j] for i in S]) == demand[j]

In [20]:
prob.solve()

1

In [21]:
for i in prob.variables():
    print(i.name, "=", i.varValue)
print('Status', LpStatus[prob.status])
print(pulp.value(prob.objective))

Route_A_1 = 0.0
Route_A_2 = 40.0
Route_A_3 = 10.0
Route_A_4 = 30.0
Route_B_1 = 50.0
Route_B_2 = 0.0
Route_B_3 = 10.0
Route_B_4 = 0.0
Route_C_1 = 0.0
Route_C_2 = 0.0
Route_C_3 = 50.0
Route_C_4 = 0.0
Status Optimal
2870.0


### 불균형 수송 문제($S_i\neq D_j$)

In [65]:
prob = LpProblem("Unbalanced Transportation", LpMinimize)

In [66]:
S = ["A", "B", "C"]
D = ["1", "2", "3", "4"]
costs = [[21, 12, 25, 11],
         [13, 10, 21, 17],
         [12, 14, 19, 12]]

supply = dict(zip(S, [80, 60, 50]))
demand = dict(zip(D, [60, 50, 80, 40]))

In [67]:
opt_costs = makeDict([S, D], costs, 0)

In [68]:
x = LpVariable.dicts('Route', (S, D), lowBound=0)
x

{'A': {'1': Route_A_1, '2': Route_A_2, '3': Route_A_3, '4': Route_A_4},
 'B': {'1': Route_B_1, '2': Route_B_2, '3': Route_B_3, '4': Route_B_4},
 'C': {'1': Route_C_1, '2': Route_C_2, '3': Route_C_3, '4': Route_C_4}}

In [69]:
routes = [(i, j) for i in S for j in D]

In [70]:
prob += lpSum([x[s][d]*opt_costs[s][d] for (s, d) in routes]) # objective function

# constraints
for i in S:
    prob += lpSum([x[i][j] for j in D]) == supply[i]

for j in D:
    prob += lpSum([x[i][j] for i in S]) <= demand[j]

In [71]:
prob.solve()

1

In [72]:
for i in prob.variables():
    print(i.name, "=", i.varValue)
print('Status', LpStatus[prob.status])
print(pulp.value(prob.objective))

Route_A_1 = 0.0
Route_A_2 = 40.0
Route_A_3 = 0.0
Route_A_4 = 40.0
Route_B_1 = 50.0
Route_B_2 = 10.0
Route_B_3 = 0.0
Route_B_4 = 0.0
Route_C_1 = 10.0
Route_C_2 = 0.0
Route_C_3 = 40.0
Route_C_4 = 0.0
Status Optimal
2550.0


### 단일수송이 아닌 복합 수송문제 분석사례

In [75]:
S = ["A", "B"]
D = ["1", "2", "3"]
costs = [[1, 10, 21, 12, 25],
         [10, 1, 13, 10, 21],
         [21, 13, 1, 8, 15], 
         [12, 10, 8, 1, 9], 
         [25, 21, 15, 9, 1]]

supply = dict(zip(S, [400, 500, 300, 300]))
demand = dict(zip(D, [300, 300, 300, 400, 400, 400]))

In [84]:
decision_vars = LpVariable.dicts("x", ((i) for i in range(1, 26)), 
                                 lowBound=0, cat='Integer')
print(decision_vars)

{1: x_1, 2: x_2, 3: x_3, 4: x_4, 5: x_5, 6: x_6, 7: x_7, 8: x_8, 9: x_9, 10: x_10, 11: x_11, 12: x_12, 13: x_13, 14: x_14, 15: x_15, 16: x_16, 17: x_17, 18: x_18, 19: x_19, 20: x_20, 21: x_21, 22: x_22, 23: x_23, 24: x_24, 25: x_25}


### AHP

In [30]:
import pandas as pd
import numpy as np

$$Ax=\lambda x$$

In [31]:
A = np.array([[1,     2,   3, 5, 7], 
              [1/2,   1,   1, 3, 4],
              [1/3,   1,   1, 2, 3],  
              [1/5, 1/3, 1/2, 1, 1],
              [1/7, 1/4, 1/3, 1, 1]])
A

array([[ 1.        ,  2.        ,  3.        ,  5.        ,  7.        ],
       [ 0.5       ,  1.        ,  1.        ,  3.        ,  4.        ],
       [ 0.33333333,  1.        ,  1.        ,  2.        ,  3.        ],
       [ 0.2       ,  0.33333333,  0.5       ,  1.        ,  1.        ],
       [ 0.14285714,  0.25      ,  0.33333333,  1.        ,  1.        ]])

In [32]:
w1, x1 = np.linalg.eig(A)
w1[0], x1[0]

((5.0368896454897083+0j),
 array([ 0.83057239+0.j, -0.74282877+0.j, -0.74282877-0.j,  0.88986345+0.j,
         0.88986345-0.j]))

In [33]:
from scipy.stats.mstats import gmean

#### 기하평균(geometric mean)

$$GM=\sqrt[n]{\prod_{i=1}^na_i}=\sqrt[n]{a_1a_2a_3\dots}$$
숫자들을 모두 곱해서 n 제곱근을 취해서 얻는 평균. 

기하 평균은 예를 들어 연간 경제성장률, 물가인상율, 연간 이자율, 감쇠/증폭율, 백분비, 크기 확대 비율 같이 표본들이 비율이나 배수이고 각 표본값이 연속성/연계성이 있어서 표본들을 곱한 값이 의미가 있는 경우에 주로 쓰인다. 예를 들어 한국의 2000 년 부터 2010년까지 평균경제성장률 등.

* 정합도 지수 또는 일관성 지수(consistency index, CI)

$CI=(\mu-n)/(n-1)$

* 정합성 비율

$CR=CI/RI$
<br>
<br>
<center>**AHP의 무작위 정합성 지수(random consistency index, RI)**</center>

|$n$|1|2|3|4|5|6|7|8|9|10|11|12|
|:-:|-:|-:|-:|-:|-:|-:|-:|-:|-:|-:|-:|-:|
|RI|0|0|0.52|0.89|1.11|1.25|1.35|1.40|1.45|1.49|1.51|1.54|



In [34]:
gm_A = gmean(A, axis=1)
gm_A

array([ 2.91369346,  1.43096908,  1.14869835,  0.50649568,  0.41223432])

In [35]:
weights = gm_A/sum(gm_A)
weights

array([ 0.45440614,  0.22316731,  0.17914568,  0.07899072,  0.06429015])

In [36]:
dot_A = np.dot(A, weights)
dot_A

array([ 2.28316248,  1.12364884,  0.90463361,  0.39812404,  0.32370309])

In [37]:
ww = dot_A/weights
ww

array([ 5.02449744,  5.0350064 ,  5.04970942,  5.04013686,  5.03503362])

In [38]:
# CI = (lambda-n)/(n-1)
CI = (w1[0]-5)/(5-1)
CI

(0.0092224113724270751+0j)

In [39]:
CR = CI/1.11
CR

(0.0083084787138982645+0j)

|**(기준)**|가격|기능|디자인|
|:-----:|:-:|:-:|:-:|
|**가격**|1|2|4|
|**기능**|1/2|1|3|
|**디자인**|1/4|1/3|1|


|**(가격)**|제품 A|제품 B|제품 C|
|:-----:|:-:|:-:|:-:|
|**제품 A**|1|2|3|
|**제품 B**|1/2|1|2|
|**제품 C**|1/3|1/2|1|

|**(기능)**|제품 A|제품 B|제품 C|
|:-----:|:-:|:-:|:-:|
|**제품 A**|1|3|5|
|**제품 B**|1/3|1|2|
|**제품 C**|1/5|1/2|1|


|**(디자인)**|제품 A|제품 B|제품 C|
|:-----:|:-:|:-:|:-:|
|**제품 A**|1|3|2|
|**제품 B**|1/3|1|1/2|
|**제품 C**|1/2|2|1|

In [40]:
# 평가기준별 선호도 조사
cc = np.array([[1, 2, 4], [1/2, 1, 3], [1/4, 1/3, 1]])

# 제품별 가격 선호도 조사
p1 = np.array([[1, 2, 3], [1/2, 1, 2], [1/3, 1/2, 1]])

# 제품별 기능 선호도 조사
p2 = np.array([[1, 3, 5], [1/3, 1, 2], [1/5, 1/2, 1]])

# 제품별 디자인 선호도 조사
p3 = np.array([[1, 3, 2], [1/3, 1, 1/2], [1/2, 2, 1]])

In [41]:
# 평가기준 분석
w1, x1 = np.linalg.eig(cc)
print("고유값 =", w1[0])
print("고유벡터 =", x1[0])

gm_A = gmean(cc, axis=1)
weights = gm_A/sum(gm_A)
print("비교대상 중요도 = ", weights)

# CI = (lambda-n)/(n-1)
CI = (w1[0]-3)/(3-1)
print("CI =", CI)

CR = CI/0.52
print("CR =", CR)

고유값 = (3.01829470729+0j)
고유벡터 = [ 0.85271323+0.j  0.85271323+0.j  0.85271323-0.j]
비교대상 중요도 =  [ 0.55842454  0.31961826  0.12195719]
CI = (0.00914735364482+0j)
CR = (0.0175910647016+0j)


In [42]:
x1.T[0]

array([ 0.85271323+0.j,  0.48805649+0.j,  0.18622840+0.j])

In [43]:
len(x1)

3

In [44]:
def AHP(matrix):
    # import numpy as np
    # from scipy.stats.mstats import gmean
    w, x = np.linalg.eig(matrix)
    gm = gmean(matrix, axis=1)
    weight = gm/sum(gm)
    CI = (w[0]-len(x))/(len(x)-1)
    AHP_RI = [0, 0, 0.52, 0.89, 1.11, 1.25, 1.35, 1.40, 1.45, 1.49, 1.51, 1.54]
    CR = CI/AHP_RI[len(x)-1]
    
    print("고유값 =", w[0])
    print("고유벡터 =", x.T[0])
    print("비교대상 중요도 = ", weight)
    print("CI =", CI)
    print("RI =", AHP_RI[len(x)-1])
    print("CR =", CR)
    return weight

In [45]:
w_cc = AHP(cc)

고유값 = (3.01829470729+0j)
고유벡터 = [ 0.85271323+0.j  0.48805649+0.j  0.18622840+0.j]
비교대상 중요도 =  [ 0.55842454  0.31961826  0.12195719]
CI = (0.00914735364482+0j)
RI = 0.52
CR = (0.0175910647016+0j)


In [46]:
w_p1 = AHP(p1)

고유값 = (3.00920271271+0j)
고유벡터 = [ 0.84679693+0.j  0.46601031+0.j  0.25645536+0.j]
비교대상 중요도 =  [ 0.53961455  0.29696133  0.16342412]
CI = (0.00460135635714+0j)
RI = 0.52
CR = (0.00884876222527+0j)


In [47]:
w_p2 = AHP(p2)

고유값 = (3.00369459806+0j)
고유벡터 = [ 0.92811934+0.j  0.32875799+0.j  0.17467875+0.j]
비교대상 중요도 =  [ 0.64832901  0.22965079  0.12202019]
CI = (0.00184729903182+0j)
RI = 0.52
CR = (0.00355249813811+0j)


In [48]:
w_p3 = AHP(p3)

고유값 = (3.00920271271+0j)
고유벡터 = [ 0.84679693+0.j  0.25645536+0.j  0.46601031+0.j]
비교대상 중요도 =  [ 0.53961455  0.16342412  0.29696133]
CI = (0.00460135635714+0j)
RI = 0.52
CR = (0.00884876222527+0j)


In [49]:
pv1 = w_cc[0] * w_p1
pv2 = w_cc[1] * w_p2
pv3 = w_cc[2] * w_p3

In [50]:
result = np.c_[pv1, pv2, pv3].sum(axis=1)
print(result)

[ 0.57436168  0.25916183  0.16647649]


In [51]:
cc = np.array([[1, 3, 5], [1/3, 1, 3], [1/5, 1/3, 1]])
p1 = np.array([[1, 1/3, 1/5], [3, 1, 1/3], [5, 3, 1]])
p2 = np.array([[1, 1/3, 3], [3, 1, 5], [1/3, 1/5, 1]])

In [52]:
# 엑셀 경영과학
w_cc = AHP(cc)

고유값 = (3.03851109056+0j)
고유벡터 = [ 0.91614200+0.j  0.37147738+0.j  0.15062670+0.j]
비교대상 중요도 =  [ 0.63698557  0.25828499  0.10472943]
CI = (0.0192555452791+0j)
RI = 0.52
CR = (0.0370298947675+0j)


In [53]:
w_p1 = AHP(p1)

고유값 = (3.03851109056+0j)
고유벡터 = [ 0.15062670+0.j  0.37147738+0.j  0.91614200+0.j]
비교대상 중요도 =  [ 0.10472943  0.25828499  0.63698557]
CI = (0.0192555452791+0j)
RI = 0.52
CR = (0.0370298947675+0j)


In [54]:
w_p2 = AHP(p2)

고유값 = (3.03851109056+0j)
고유벡터 = [ 0.37147738+0.j  0.91614200+0.j  0.15062670+0.j]
비교대상 중요도 =  [ 0.25828499  0.63698557  0.10472943]
CI = (0.0192555452791+0j)
RI = 0.52
CR = (0.0370298947675+0j)


In [55]:
# 가격을 기준으로 평가한 대안의 가중치
price = np.array([1500, 1700, 2100])
cal_price = 1/price
w_p3 = cal_price/sum(cal_price)
w_p3

array([ 0.38511327,  0.33980583,  0.27508091])

In [56]:
result = np.c_[w_p1, w_p2, w_p3]
print(result)

[[ 0.10472943  0.25828499  0.38511327]
 [ 0.25828499  0.63698557  0.33980583]
 [ 0.63698557  0.10472943  0.27508091]]


In [57]:
# 결과
result.dot(w_cc)

array([ 0.17375497,  0.3646353 ,  0.46160973])

### ANP(Analytic Network Process)

In [58]:
# 평가기준별 선호도 조사
cc = np.array([[1, 2, 4], [1/2, 1, 3], [1/4, 1/3, 1]])

# 제품별 가격 선호도 조사
p1 = np.array([[1, 2, 3], [1/2, 1, 2], [1/3, 1/2, 1]])

# 제품별 기능 선호도 조사
p2 = np.array([[1, 3, 5], [1/3, 1, 2], [1/5, 1/2, 1]])

# 제품별 디자인 선호도 조사
p3 = np.array([[1, 3, 2], [1/3, 1, 1/2], [1/2, 2, 1]])

In [59]:
w_cc = AHP(cc)

고유값 = (3.01829470729+0j)
고유벡터 = [ 0.85271323+0.j  0.48805649+0.j  0.18622840+0.j]
비교대상 중요도 =  [ 0.55842454  0.31961826  0.12195719]
CI = (0.00914735364482+0j)
RI = 0.52
CR = (0.0175910647016+0j)


In [60]:
w_p1 = AHP(p1)

고유값 = (3.00920271271+0j)
고유벡터 = [ 0.84679693+0.j  0.46601031+0.j  0.25645536+0.j]
비교대상 중요도 =  [ 0.53961455  0.29696133  0.16342412]
CI = (0.00460135635714+0j)
RI = 0.52
CR = (0.00884876222527+0j)


In [61]:
w_p2 = AHP(p2)

고유값 = (3.00369459806+0j)
고유벡터 = [ 0.92811934+0.j  0.32875799+0.j  0.17467875+0.j]
비교대상 중요도 =  [ 0.64832901  0.22965079  0.12202019]
CI = (0.00184729903182+0j)
RI = 0.52
CR = (0.00355249813811+0j)


In [62]:
w_p3 = AHP(p3)

고유값 = (3.00920271271+0j)
고유벡터 = [ 0.84679693+0.j  0.25645536+0.j  0.46601031+0.j]
비교대상 중요도 =  [ 0.53961455  0.16342412  0.29696133]
CI = (0.00460135635714+0j)
RI = 0.52
CR = (0.00884876222527+0j)


In [63]:
# 슈퍼 매트릭스
s1 = np.zeros(7)
s1[1:4] = w_cc

s2 = np.zeros(7)
s2[4:7] = w_p1

s3 = np.zeros(7)
s3[4:7] = w_p2

s4 = np.zeros(7)
s4[4:7] = w_p3

s5 = np.zeros(7)
s5[4:7] = [1, 0, 0]

s6 = np.zeros(7)
s6[4:7] = [0, 1, 0]

s7 = np.zeros(7)
s7[4:7] = [0, 0, 1]

In [64]:
ss = np.c_[s1, s2, s3, s4, s5, s6, s7]
ss.dot(ss)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.57436168,  0.53961455,  0.64832901,  0.53961455,  1.        ,
         0.        ,  0.        ],
       [ 0.25916183,  0.29696133,  0.22965079,  0.16342412,  0.        ,
         1.        ,  0.        ],
       [ 0.16647649,  0.16342412,  0.12202019,  0.29696133,  0.        ,
         0.        ,  1.        ]])